
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'acr-aks'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t usamlabacr02.azurecr.io/web-game:tag 2048-game
      az acr login -n usamlabacr02
      docker push usamlabacr02.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'acr-aks'
    azureResourceGroup: 'usaLabrg02'
    kubernetesCluster: 'usaLab-aks02'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'acr-aks'
    azureContainerRegistry: 'usamlabacr02.azurecr.io'
    forceUpdate: false