name: Greet Someone

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet using composite action
        uses: ./.github/actions/greeter
        with:
          who-to-greet: ${{ secrets.MY_SECRET_NAME }}
