name: AWS build and Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: Checkout file completed
      run: echo "files are out but we need only htmt files"

