name: AWS build and Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: Checkout file completed
      run: echo "files are out but we need only htmt files"
    - uses: NuGet/setup-nuget@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install -g yarn
    - name: install npm yarn
      run: yarn install --frozen-lockfile
    - run: yarn build

