name: AWS build and Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: Checkout file completed
      run: echo "files are out but we need only htmt files"
    - uses: NuGet/setup-nuget@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install -g yarn
    - name: install npm yarn
      run: yarn install --frozen-lockfile
    
    - uses: actions\upload-Artifact@v3
      with:
        name: artnamemyapp
        path: 2048-game/index.html
        if-no-files-found: warn
        retention-days: 10

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS Secret Access Key. Required if aws-access-key-id is provided.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo deployment started
      #  - run: aws s3 sync ./2048-game/ s3://usa-static-website-nextjs  
