name: Build and Deploy Container App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4.1.5    
    - uses: azure/docker-login@v2
      with:
        login-server: usamacontainer01.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: build Docker container reg
      run: |
        docker build . -t usamacontainer01.azurecr.io/web-game:${{ github.sha }}
        docker push usamacontainer01.azurecr.io/web-game:${{ github.sha }}

    
        
    
    
    

          
