name: Build and Deploy Container App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4.1.5    
    - uses: azure/docker-login@v2
      with:
        login-server: usamacontainer01.azurecr.io
        username: secrets.
        password: secrets.
     - run:  |
         docker build . -t  usamacontainer01.azurecr.io/web-game:tag 2048-game
         docker push usamacontainer01.azurecr.io/web-game:tag
        
    
    
    

          
