name: Build and Deploy Container App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4.1.5    
    - uses: azure/docker-login@v2
      with:
        login-server: test.azurecr.io
        
    
    
    

          
