
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
        - name: Checkout
        - uses: actions/checkout@v4.1.5
          
