name: create and publish
on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string

jobs:
  Deployment:
     runs-on: ubuntu-latest

     steps:
      - name: ${{ inputs.tag }} Package execution
        run: echo ${{ inputs.image_name }} and ${{ inputs.tag }}
      - run: echo deployment started
      - uses: actions/download-artifact@v3
        with:
          name: WebGameApp4s3
      - run: ls -R
    