name: AWS Web Deployment
on: 
  workflow_call:
    inputs:
      env-flow:
        required: true
        type: string
      tag:
        type: string
    secrets:
        aws-access-id:
          required: true
        aws-secret-key:
          required: true      

jobs:
  Deployment:
     runs-on: ubuntu-latest

     steps:
      - name: ${{ inputs.tag }} Package execution
        run: echo ${{ inputs.env-flow }} and ${{ inputs.tag }}
      - run: echo deployment started
      - uses: actions/download-artifact@v3
        with:
          name: WebGameApp4s3
      - run: ls -R
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
       # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
          aws-access-key-id: ${{ secrets.aws-access-id }}
        # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{ secrets.aws-secret-key }}
      - run: aws s3 sync ./ s3://usa-static-website-nextjs  
