name: AWS Web build

on: 
    pull_request:
    workflow_dispatch:
      inputs:
        Env-flow:
            description: "Select your deployment workflow?"
            default: SandBox
            type: choice
            options: 
              - SandBox
              - Dev to Production
jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: NuGet/setup-nuget@v2
        name: Setup Nuget Package
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install -g yarn
        name: install npm yarn
      - run: yarn test
        name: Run Unit Testing  
        
      - uses: actions/upload-artifact@v3
        with:
          name: WebGameApp4s3
          path: ./2048-game/
          if-no-files-found: warn
          retention-days: 10
  
  Analysis:
    needs: Build-Package
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            -Dsonar.projectKey=usamasha-hotmail_acr-aks
            -Dsonar.organization=usamasha-hotmail
          projectBaseDir: .  


  SandBox-Env:
    needs: Build-Package
    if:  ${{ inputs.Env-flow != 'Dev to Production' }} 
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: ${{ inputs.Env-flow }}
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  DEV-Env:
    needs: Build-Package
    if:  ${{ inputs.Env-flow == 'Dev to Production' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: DEV
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Staging-Env:
    needs: DEV-Env
    if:  ${{ inputs.Env-flow == 'Dev to Production' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: Stage
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Prod-Env:
    needs: Staging-Env
    if:  ${{ inputs.Env-flow == 'Dev to Production' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: Prod
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        