name: AWS Web build

on: 
    workflow_dispatch:
      inputs:
        Env-flow:
            description: "Select your env. workflow?"
            default: SandBox
            type: choice
            options: 
              - SandBox
              - Dev to Production
jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: NuGet/setup-nuget@v2
        name: Setup Nuget Package
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install -g yarn
        name: install npm yarn
        
      - uses: actions/upload-artifact@v3
        with:
          name: WebGameApp4s3
          path: ./2048-game/
          if-no-files-found: warn
          retention-days: 10

  SandBox-Env:
    needs: Build-Package
    if:  ${{ inputs.Env-flow == 'SandBox' }} 
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: ${{ inputs.Env-flow }}
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  DEV-Env:
    needs: Build-Package
    if:  ${{ inputs.Env-flow != 'SandBox' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: DEV
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Staging-Env:
    needs: DEV-Env
    if:  ${{ inputs.Env-flow != 'SandBox' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: Stage
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Prod-Env:
    needs: Stage-Env
    if:  ${{ inputs.Env-flow != 'SandBox' }}
    uses: usamasha-hotmail/ACR-AKS/.github/workflows/CD-Deploy.yml@main
    with:
        env-flow: Prod
        tag: " "
    secrets:
        aws-access-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        